
services:
  app:
    build:
      context: .
      args:
        DEV: true
    ports:
      - "8010:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "/py/bin/python manage.py runserver 0.0.0.0:8000"
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:latest
  #   environment:
  #       POSTGRES_DB: mydb
  #       POSTGRES_USER: myuser
  #       POSTGRES_PASSWORD: mypassword