---
name: Checks

on: [push]

jobs:
    test-lint:
        name: Lint and Test
        runs-on: ubuntu-20.04
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Test
              run: docker compose run --rm app sh -c "/py/bin/python manage.py test"

            - name: Lint
              run: docker compose run --rm app sh -c "/py/bin/flake8"


            # - name: Set up Python 3.9
            #   uses: actions/setup-python@v2
            #   with:
            #       python-version: 3.8

            # - name: Install dependencies
            #   run: |
            #       python -m pip install --upgrade pip
            #       pip install -r requirements.txt

            # - name: Lint with flake8
            #   run: |
            #       flake8 .

            # - name: Test with pytest
            #   run: |
            #       pytest